<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
            DB::table('plans')->truncate();

        $plans = [
            [
                'id'              => Str::uuid(),
                'name'            => 'Free',
                'plan_type'       => 'free',
                'billing_cycle'   => 'free',
                'price_usd_cents' => 0,
                'max_seats'       => 1,
                'is_free_forever' => true,
                'is_active'       => true,
                'stripe_price_id' => null,
                'display_order'   => 1,
                'features'        => json_encode([
                    'n5_access'        => true,
                    'n4_access'        => false,
                    'n3_access'        => false,
                    'n2_access'        => false,
                    'n1_access'        => false,
                    'mock_exams'       => false,
                    'audio_lessons'    => false,
                    'offline_access'   => false,
                    'ai_hints'         => false,
                    'certificates'     => false,
                    'full_analytics'   => false,
                    'ads_shown'        => true,
                    'lesson_limit'     => 5,
                    'flashcard_limit'  => 100,
                    'test_limit'       => 1,
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'              => Str::uuid(),
                'name'            => 'Individual Pro Monthly',
                'plan_type'       => 'individual',
                'billing_cycle'   => 'monthly',
                'price_usd_cents' => 999,
                'max_seats'       => 1,
                'is_free_forever' => false,
                'is_active'       => true,
                'stripe_price_id' => 'price_pro_monthly_placeholder',
                'display_order'   => 2,
                'features'        => json_encode([
                    'n5_access'        => true,
                    'n4_access'        => true,
                    'n3_access'        => true,
                    'n2_access'        => true,
                    'n1_access'        => true,
                    'mock_exams'       => true,
                    'audio_lessons'    => true,
                    'offline_access'   => true,
                    'ai_hints'         => true,
                    'certificates'     => true,
                    'full_analytics'   => true,
                    'ads_shown'        => false,
                    'lesson_limit'     => null,
                    'flashcard_limit'  => null,
                    'test_limit'       => null,
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'              => Str::uuid(),
                'name'            => 'Individual Pro Annual',
                'plan_type'       => 'individual',
                'billing_cycle'   => 'annual',
                'price_usd_cents' => 799,
                'max_seats'       => 1,
                'is_free_forever' => false,
                'is_active'       => true,
                'stripe_price_id' => 'price_pro_annual_placeholder',
                'display_order'   => 3,
                'features'        => json_encode([
                    'n5_access'        => true,
                    'n4_access'        => true,
                    'n3_access'        => true,
                    'n2_access'        => true,
                    'n1_access'        => true,
                    'mock_exams'       => true,
                    'audio_lessons'    => true,
                    'offline_access'   => true,
                    'ai_hints'         => true,
                    'certificates'     => true,
                    'full_analytics'   => true,
                    'ads_shown'        => false,
                    'lesson_limit'     => null,
                    'flashcard_limit'  => null,
                    'test_limit'       => null,
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'              => Str::uuid(),
                'name'            => 'Team',
                'plan_type'       => 'team',
                'billing_cycle'   => 'monthly',
                'price_usd_cents' => 699,
                'max_seats'       => 20,
                'is_free_forever' => false,
                'is_active'       => true,
                'stripe_price_id' => 'price_team_monthly_placeholder',
                'display_order'   => 4,
                'features'        => json_encode([
                    'n5_access'        => true,
                    'n4_access'        => true,
                    'n3_access'        => true,
                    'n2_access'        => true,
                    'n1_access'        => true,
                    'mock_exams'       => true,
                    'audio_lessons'    => true,
                    'offline_access'   => true,
                    'ai_hints'         => true,
                    'certificates'     => true,
                    'full_analytics'   => false,
                    'ads_shown'        => false,
                    'team_leaderboard' => true,
                    'assign_tests'     => true,
                    'basic_admin'      => true,
                    'lesson_limit'     => null,
                    'flashcard_limit'  => null,
                    'test_limit'       => null,
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'              => Str::uuid(),
                'name'            => 'Institution',
                'plan_type'       => 'institution',
                'billing_cycle'   => 'monthly',
                'price_usd_cents' => 0,
                'max_seats'       => 500,
                'is_free_forever' => false,
                'is_active'       => true,
                'stripe_price_id' => null,
                'display_order'   => 5,
                'features'        => json_encode([
                    'n5_access'        => true,
                    'n4_access'        => true,
                    'n3_access'        => true,
                    'n2_access'        => true,
                    'n1_access'        => true,
                    'mock_exams'       => true,
                    'audio_lessons'    => true,
                    'offline_access'   => true,
                    'ai_hints'         => true,
                    'certificates'     => true,
                    'full_analytics'   => true,
                    'ads_shown'        => false,
                    'team_leaderboard' => true,
                    'assign_tests'     => true,
                    'basic_admin'      => true,
                    'advanced_admin'   => true,
                    'bulk_export'      => true,
                    'sso'              => true,
                    'api_access'       => true,
                    'lesson_limit'     => null,
                    'flashcard_limit'  => null,
                    'test_limit'       => null,
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('plans')->insert($plans);

        $this->command->info('✅ Plans seeded — 5 plans created.');
    }
}